### PR TITLE
Trying to add features.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by Garyfallidis** [comment]
@arokem the 64 bit machines with Python 3.6 are passing! 👯 💯 👶 
Only the x86 machines have an issue which you can resolve by changing
CONDA_INSTALL_LOCN=C:\\Miniconda36
to
CONDA_INSTALL_LOCN=C:\\Miniconda35
Let me know when the binaries are up in conda to try them!

**Comment by arokem** [comment]
OK - just pushed that. Hopefully we'll wake up tomorrow to all green!

**Comment by Garyfallidis** [comment]
ALL GREEN!!! Yehaah! Merge!

**Comment by Garyfallidis** [comment]
Will the packages be available immediately after merging this?

**Comment by isuruf** [comment]
No. After merging, CI has to run again before the package is uploaded to anaconda.org.

**Comment by arokem** [comment]
Thanks everyone for your help with this!

**Comment by Garyfallidis** [comment]
And special thanks to @isuruf!

**Pull request merged**
