### PR TITLE
ENH: Add Python 3.11

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
Looks like it's dependencies... opened https://github.com/conda-forge/matplotlib-feedstock/pull/336 at least. Not sure if `pytables` / `lzo` that it mentions is relevant or not

**Comment by larsoner** [comment]
Segfault on arm64 is expected https://github.com/conda-forge/conda-forge.github.io/issues/1823 . I'll restart once matplotlib merges their PR

**Comment by larsoner** [comment]
@conda-forge-admin, please restart ci

**Comment by larsoner** [comment]
@conda-forge-admin, please restart ci

**Comment by larsoner** [comment]
This will be held up by statsmodels (https://github.com/conda-forge/statsmodels-feedstock/pull/55, https://github.com/statsmodels/statsmodels/issues/8287)

**Comment by EwoutH** [comment]
Statsmodels 0.13.3 is released, with Python 3.11 wheels!

**Comment by skoudoro** [comment]
@conda-forge-admin, please restart ci

**Comment by larsoner** [comment]
3.11 on conda forge is still a work in progress, though

https://github.com/conda-forge/statsmodels-feedstock/pull/56#issuecomment-1299111182

**Comment by skoudoro** [comment]
Sorry, too much excitement 😀 .

Thank you for this @larsoner and all.

**Comment by larsoner** [comment]
Now it's in, lets see if CDNs have updated yet or not...

@conda-forge-admin, please restart ci

**Comment by larsoner** [comment]
Ahh this is the same problem that statsmodels had. By any chance was your `sdist` on PyPI created with a Cython that produced `.c` files that are not 3.11 compatible? That was the problem with statsmodels, and the error message here looks the same

**Comment by skoudoro** [comment]
> By any chance was your sdist on PyPI created with a Cython that produced .c files that are not 3.11 compatible?

I believe so.

It means we need to cut a new release. we should avoid to update the previous sdist.

**Comment by larsoner** [comment]
> It means we need to cut a new release. we should avoid to update the previous sdist.

Instead of waiting for this, I implemented a patch that forces re-cythonization of the files in the released sdist. However, this fails, with stuff like:
```
dipy/core/interpolation.pyx:11:0: 'dipy/align/fused_types.pxd' not found
```
and
```
Error compiling Cython file:
------------------------------------------------------------
...
                 object sphere,
                 int sh_order=0,
                 double tol=1e-2):
        cdef:
            double b_range
            np.ndarray x, y, z, r
           ^
------------------------------------------------------------

dipy/direction/pmf.pyx:108:12: 'np' is not a cimported module
```
This suggests to me that the `sdist` itself is also perhaps missing some files that would allow people to re-run Cython. And there are maybe (?) some bugs in the `pyx` themselves -- for that second one for example I can change the `np.ndarray` to `cnp.ndarray` and it at least doesn't complain there anymore.

In any case, it does look like this problem will need to be solved by a new release. Feel free to close this PR, or we can push commits to it later to remove the patch and bump the version + hash once a new release is made

**Comment by larsoner** [comment]
Looks like `dipy` and `numba` are the two remaining Python 3.11 blockers for MNE-Python to be able to use a 3.11 stack at least. Any ideas on a timeline for a 1.5.1 or 1.6.0 that would be 3.11 compatible?

**Comment by skoudoro** [comment]
Hi @larsoner, 

In our side, it seems that h5py does not have any python 3.11 wheels on PiPy (Which is strange since they have it on conda-forge). it is a core dependency and it is problematic to cut a release without this. 

Also some optional depencencies like vtk are missing. Even if it is fine, I can already see coming users complaining that visualization does not work as soon as we have a release for python 3.11. So, we might release just a dev0 version as soon as h5py is available to avoid unhappy users :-)

**Comment by larsoner** [comment]
Another way forward I just realized to make everything work on conda-forge on 3.11: I could push a patch for the .c compiled with a newer Cython on my system. Then this patch can just be removed when you eventually release. 

I just did this for Mayavi and it was pretty painless actually. I'll see if it makes things green here...

**Comment by larsoner** [comment]
Looks like it was sufficient to add back in the `.pxd` files and force re-cythonization, ready for review/merge from my end!

**Review by skoudoro — APPROVED** [review]
Thank you very much for this work @larsoner.

I did know about conda patches and just learn about it. That is really convenient. 

I will go ahead and merge this PR, and add a reminder to remove this patch when we are ready. 

Thanks again

**Pull request merged**
