### PR TITLE
Full test run on feedstock.

### PR DESCRIPTION
**Pull request by arokem**
Adding some testing, to see how terrible that would be

### CODE REVIEW

**Comment by astrofrog** [comment]
@arokem - each build is taking 1h and timing out, and this is holding back the whole appveyor queue. Can we kill the AppVeyor jobs? (edit: looks like it has been killed - thanks to whoever did that!)

**Comment by ocefpaf** [comment]
@arokem please don't send PRs from master as those builds will be uploaded before the merge! (Not to mention that it will run the CIs twice here.)

The recommended workflow is to fork-branch-PR-merge.

**Comment by jakirkham** [comment]
So, it appears the full test suite is out of scope here. I'm glad we have learned this (after all much of this is a learning experience for all of us 😉).

Given that it is so long and we share the AppVeyor queue here, one thing you might want to try, @arokem, which will help you explore this while you figure out the right amount of tests to use is to fork the feedstock and enable CI on your fork. Once you have figured out a reasonable amount of testing that is within scope, please feel free to open a PR.

**Comment by arokem** [comment]
Apologies for holding up other jobs!

I am not so sure that I understand the recommended workflow (and how it differs from what I did here). What I did here: 
1. Fork the repo
2. Create a new branch with the changes
3. Make a PR from that branch, relative to the root node (conda-forge/dipy-feedstock)

What's the recommended series of steps to make sure that the feedstock gets tested on the CI? Should I create the PR relative to my own fork?

**Comment by arokem** [comment]
I stand corrected - did not do this off my fork, though I do have one...

**Comment by jakirkham** [comment]
So, maybe the remote URLs in git got messed up? The branch basically should have been on your own fork.

**Comment by arokem** [comment]
So what is the right level of testing? In the course of development, we run the test suite in full, of course. But we want to make sure that the conda-forge releases would work well on users' machines (we've already run into some incompatibilities in the past: https://github.com/nipy/dipy/issues/852). Should we separately test this on a build-bot? That seems to defeat the purpose (but I might be over-extending the purpose...).

**Comment by jakirkham** [comment]
Yeah, that's a good question. The main point of the CIs here is to build a binary and make sure this binary works (i.e. it is linked correctly, CLIs exist and can be called, hopefully catch numerical errors if it is something low-level like `gmp`, `fftw`, a BLAS, etc.). In other words, conda-forge makes it simpler for you to ship easy to install releases with some guarantees.

Ensuring overall compatibility between packages IMHO feels like something that should be determined before a release. This needs to happen before a release as one must be able to state what versions of a dependency a package supports. Does that make sense?

**Pull request closed without merging**
