### PR TITLE
New Release 0.14.0

### PR DESCRIPTION
**Pull request by skoudoro**
Recipe to update dipy conda package

### CODE REVIEW

**Comment by skoudoro** [comment]
Hi @arokem, Do you have any idea for fixing those errors?

**Comment by arokem** [comment]
I don't. Maybe ping the conda-forge gitter channel for advice?

It seems that the issue is that `touch: cannot touch
`/home/conda/feedstock_root/build_artifacts/conda-forge-build-done': No
such file or directory`

Seems like the recipe is missing a `mkdir` somewhere before this?

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin please rerender

**Comment by skoudoro** [comment]
Thank you @arokem for the feedback

Thank you really much @isuruf for updating our recipe

merging

**Pull request merged**
